### ISSUE TITLE
Bug with create new model in rails_admin

### ISSUE THREAD

**Issue by eniwito** [zcpdog/rails_admin_aasm#10]
Hi! I'm using rails_admin 0.8.1. When i go to the create new record in model i have this error: `No route matches {:action=>"state", :attr=>:status, :controller=>"rails_admin/main", :event=>:process, :id=>nil, :model_name=>#<RailsAdmin::AbstractModel:0x007f9f3ace8688 @model_name="Stage", @adapter=:active_record>} missing required keys: [:id]`

http://localhost:3000/admin/model_name/new - this path not work

Because new model haven't id. How fix this?

**Comment by eniwito** [comment]
http://localhost:3000/admin/model_name/new - this path not work

**Comment by zcpdog** [comment]
Hi @eniwito , it doesn't work at new page. please use it at list page
