### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by rstormsf** [zcpdog/rails_admin_aasm#3]
`undefined method`state_event' for #Opportunity:0x007ff3cc49d258`

```
rails_admin do
  edit do
    field :state, :state
  end
  state({
    events: {completed: 'btn-danger', created: 'btn-warning', approved_by_agent: 'btn-success'},
    states: {complete: 'label-important', create: 'label-warning', approve_by_agent: 'label-success'}
  })
  end
```

**Comment by troyanryller** [comment]
@rstormsf  try adding

```
  attr_accessor :state_event
```

to your model.

**Comment by rstormsf** [comment]
Added. Works. But I'm trying to understand how to use it. I see the label of current state and what is weird is: my state name is `created`, if I specify state: `create` - it shows in UI, if I specify as `created` - it doesn't. 
2)I can't understand how to display buttons for events.

**Comment by rstormsf** [comment]
No worries - now it works as expected. 
Only question - how to only add this field with the rest of the fields?

**Update:
figured it:

```
rails_admin do
    edit do
      configure :state, :state do
      end

    end
  end
```

**Comment by rstormsf** [comment]
Another problem: 
When events are called - > it doesn't save to db :-(
#4 What do I do wrong?

**Comment by troyanryller** [comment]
I include all fields + aasm field in this way:

``` ruby
    rails_admin do
      list do
        field :aasm_state, :state
        include_all_fields
      end

      edit do
        field :aasm_state, :state
        include_all_fields
      end
    end
```

**Comment by nakamuraagatha** [comment]
i got erorr 

```
 else
        match = match_attribute_method?(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end
```

**Comment by zcpdog** [comment]
@nakamuraagatha  can you post the error backtrace and how did you use this gem?
