### ISSUE TITLE
undefined method `status_event'

### ISSUE THREAD

**Issue by TangMonk** [zcpdog/rails_admin_aasm#6]
Hi, thanks for your gem. but it throw following error:

![image](https://cloud.githubusercontent.com/assets/3498786/15037852/13dd7c4e-12d1-11e6-8e51-161999f635a4.png)

I am using aasm 4.5.1

**Comment by TangMonk** [comment]
And I cannot change state in edit form,
And What's the no event button for ?

![image](https://cloud.githubusercontent.com/assets/3498786/15038288/067eb80c-12d5-11e6-8b30-a161cdb890d1.png)

**Comment by zcpdog** [comment]
for your first question, did you tell aasm which field you are using ? 
aasm column: :the_field do
xxx
end

for the second question, there is no such event in this gem, can you post your model of the aasm part?

Thanks

**Comment by TangMonk** [comment]
@zcpdog , thanks for your reply, 

first, in 'rails_admin_aasm/app/views/rails_admin/main/_form_state.html.haml', if I remove `+ '_event'` in line 2 with following will works(i am using aasm 4.5.1)

```
.state-widget
  = form.hidden_field field.method_name.to_s
  = field.form_value
  :javascript
    $(function() {
      $('.state-btn').off('click').click(function(e){
        e.preventDefault();
        var $t = $(this), d = $t.data();
        var $i = $t.parents('.state-widget').find('input')
        $i.val(d.event);
        $t.siblings().removeClass('active')
        $t.addClass('active')
      })
    })
```

second, this following is my model of aasm part:

```
  aasm column: "status" do
    state :unpaid, initial: true
    state :unused
    state :refunding
    state :refunded
    state :deleted
    state :finished

    event :pay do
      transitions from: :unpaid, to: :unused, after: :after_pay
    end

    event :request_refund do
      transitions from: :unused, to: :refunding
    end

    event :refund do
      transitions from: :refunding, to: :refunded, after: :after_refund
    end

    event :reject_refund do
      transitions from: :refunding, to: :unused
    end

    event :delete do
      transitions from: [:unpaid, :refunded, :finished], to: :deleted
    end

    event :finish do
      transitions from: :unused, to: :finished
    end
  end
```

I am thinking the `no_event` button is necessary ?
